name: Test `read-ci` action

on:
    push:
        paths:
            - src/read-ci.ts
            - src/__tests__/__read-ci__.ts
            - __tests__/read-ci/__read-ci__.json
            - .github/workflows/read-ci_test.yml
    pull_request:
        paths:
            - src/read-ci.ts
            - src/__tests__/__read-ci__.ts
            - __tests__/read-ci/__read-ci__.json
            - .github/workflows/read-ci_test.yml
jobs:
    ci:
        runs-on: ubuntu-latest
        outputs:
            os: ${{ steps.run.outputs.os }}
            node: ${{ steps.run.outputs.node }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - id: run
              name: Set outputs from configuration file
              uses: marcozac/gh-actions/read-ci@read-ci
              with:
                  ciFile: __tests__/read-ci/__read-ci__.json
                  log: |
                      os
                      node

    test_output:
        needs: ci
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - id: print-outputs
              run: |
                  echo ${{ needs.ci.outputs.os }}
                  echo ${{ needs.ci.outputs.node }}

            - id: test
              name: Test ci step outputs
              uses: marcozac/gh-actions/__tests__/read-ci@read-ci-test
              with:
                  os: ${{ needs.ci.outputs.os }}
                  node: ${{ needs.ci.outputs.node }}

    test_matrix:
        needs: ci
        strategy:
            matrix:
                os: ${{ fromJson(needs.ci.outputs.os) }}
        runs-on: ${{ matrix.os }}
        steps:
            - run: echo "Test successful."
